# Generated by Django 5.0.1 on 2024-01-26 14:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_category'),
        ('management', '0002_alter_category_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expense',
            new_name='Expenses',
        ),
    ]
