import type { Metadata } from "next";
import localfont from "next/font/local";
import "./globals.css";
import Header from "./components/Header.";
import { AuthProvider } from "./context/AuthContext";


const InterFont = localfont({src: './fonts/Inter.ttf'})

export const metadata: Metadata = {
  title: "Expense App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={InterFont.className}>
        <AuthProvider>
        <Header/>
        {children}
        </AuthProvider>
        </body>
    </html>
  );
}
